package com.example.springboottest1.mapper;

import com.example.springboottest1.entity.bookInfo;

public interface bookInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    int insert(bookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    int insertSelective(bookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    bookInfo selectByPrimaryKey(Long autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(bookInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(bookInfo record);
}