package com.example.springboottest1.mapper;

import com.example.springboottest1.entity.classInfo;

public interface classInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    int insert(classInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    int insertSelective(classInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    classInfo selectByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(classInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(classInfo record);
}